spring:
  application:
    name: yubi-backend
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yubi
    username: root
    password: 123456
  # Redis 配置
  # todo 需替换配置，然后取消注释
  redis:
    database: 1
    host: 192.168.0.198
    port: 6379
    timeout: 5000
    password: Nimabi687
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  rabbitmq:
    host: 192.168.0.198
    port: 5672
    password: admin152
    username: admin152
    virtual-host: /
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bi
server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
yuapi:
  client:
    secret-key: ${secret-key}
    access-key: ${access-key}
dsapi:
  client:
    api-key: sk-c78ecf4406e14b7380ef66032940a7ef
xunfei:
  client:
    appid: 84241bad
    apiSecret: OGJiYTFhYTM2ODdlN2VkZTRjNmZiNWU0
    apiKey: e2521d734c0e774e8d78c6aaba172c0c
file:
  minio:
    endpoint: http://www.huanghao.icu:9000 #存储服务域名
    accessKey: fXaaIJjyvqP9MWmycECK
    secretKey: AaUDDlqRVdCk4LSYTbLIX8UPBX9k0DuyEiiW4ahq
    bucket: hhbi   #存储桶名称
ai:
  api-key: 08d99210-fb47-40cf-96f4-af1fbe33016c